const AreaTemplate = require("../../AreaTemplate");

class MotionDetectorsAreaBinarySensor extends AreaTemplate {

  constructor(area_id, {

    area_name = area_id,
    path,
    ...options

  } = {}) {

    super(area_id, { 
      
      // Defaults
      base_path: `/config/.storage/templates/area/motion/detection/${area_id}/`,
      file_name: `motion_detectors_${area_id}_binary_sensor.yaml`,

      // Optional
      area_name,
      path,
      ...options 

    });

    this.template = this.build(area_id, { area_name });

  }

  build = (area_id = this.area_id, { area_name = this.area_name }) => 

`template:
  - binary_sensor:
      - name: "Motion Detectors ${area_name}"
        unique_id: "motion_detectors_${area_id}"
        device_class: motion
        state: >
          {% set motion_detection_enabled = is_state('switch.motion_detection_toggle_${area_id}', 'on') %}
          {% set triggered_sensors = expand(area_entities("${area_id}"))
          | selectattr('domain', 'eq', 'binary_sensor')
          | selectattr('state', 'eq', 'on')
          | rejectattr('entity_id','contains','motion_detectors_${area_id}')
          | list %}
          {{ 'on' if motion_detection_enabled and (triggered_sensors | length > 0) else 'off' }}
        icon: >
          {% if is_state('switch.motion_detection_toggle_${area_id}', 'on') %}
            mdi:motion-sensor
          {% else %}
            mdi:motion-sensor-off
          {% endif %}
        attributes:
          autogenerated: true`;

}

module.exports = MotionDetectorsAreaBinarySensor;